language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "pypy"

install:
  - apt-get install wget
  - wget http://packages.elasticsearch.org/GPG-KEY-elasticsearch && apt-key add GPG-KEY-elasticsearch && apt-get update && apt-get install elasticsearch
  # install python requirements
  - pip install coveralls
  - pip install -e .[tests]

script:
  - make test

after_success:
  - coveralls
